---
# configure VMware Workstation and build kernel modules

- name: build VMware kernel modules
  command: vmware-modconfig --console --install-all
  args:
    creates: "/lib/modules/{{ ansible_kernel }}/misc/vmnet.ko"
  become: yes

- name: load VMware kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - vmw_vmci
    - vmmon
  become: yes

- name: setup VMware Workstation license
  command: /usr/lib/vmware/bin/vmware-vmx --new-sn "{{ vmware_license_key }}"
  when: (vmware_license_key is defined ) and ( vmware_license_key | length > 0 )
  become: yes

- name: setup default netmap.conf
  command: /usr/lib/vmware/bin/vmware-vmx --new-sn "{{ vmware_license_key }}"
  when: (circleci is defined ) and ( circleci | length > 0 )
  become: yes

- name: Create systemd services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0755'
  with_fileglob:
    - "*.service"
  notify: reload systemd
  become: yes
